require("install-plugins")
require("general")

require("plugins/cmp")
require("plugins/lsp")
require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/treesitter")
require("plugins/diffview")
require("plugins/blamer")
require("plugins/indent-blankline")
require("plugins/illuminate")
require("plugins/null-ls")
require("mason").setup()

