require("dependencies.plugins.blamer")
require("dependencies.plugins.cmp")
require("dependencies.plugins.diffview")
require("dependencies.plugins.fzf")
require("dependencies.plugins.illuminate")
require("dependencies.plugins.indent-blankline")
require("dependencies.plugins.lualine")
require("dependencies.plugins.mason")
require("dependencies.plugins.nvim-tree")
require("dependencies.plugins.refactoring")
require("dependencies.plugins.treesitter")
require("dependencies.plugins.lsp")
require("dependencies.plugins.formatter")
require("dependencies.plugins.nvim-lint")

